rename_profile:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            integration: haeo_device_forecast
    profile_id:
      required: true
      selector:
        text:
    name:
      required: true
      selector:
        text:

merge_profiles:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            integration: haeo_device_forecast
    profile_ids:
      required: true
      selector:
        text:
          multiple: true
    name:
      required: true
      selector:
        text:

search_profiles:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            integration: haeo_device_forecast
